iou_lane:
  _target_: cross_view_transformer.metrics.IoUMetric
  label_indices: ${data.lane.label_indices}

iou_road:
  _target_: cross_view_transformer.metrics.IoUMetric
  label_indices: ${data.road.label_indices}